#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim :set ft=python:

"""
Create a any new roles given on the command line without any permissions set.
The Script uses the boto credentials or asks for if the option is given.

Usage:
    add_machine_roles [--ask-credentials] [--roleprefix=PREFIX]
                      [--trusted-arn=ARN] ROLE...

Options:
  -h --help            Show this
  --ask-credentials    Ask for Credentials
  --roleprefix=PREFIX  Optional Prefix for roles
  --trusted-arn=ARN    arn of the role / user allowed to assume these roles
                       Example: arn:aws:iam::123456789:user/some-user
"""

from add_aws_roles import _get_credentials, RoleAdder

from docopt import docopt


def main():
    """Main function for script execution"""
    arguments = docopt(__doc__)
    arguments['--roleprefix'] = arguments['--roleprefix'] or ""
    access_key_id = secret_access_key = None
    if arguments['--ask-credentials']:
        access_key_id, secret_access_key = _get_credentials()

    role_adder = RoleAdder(
        arguments['ROLE'],
        arguments['--roleprefix'],
        arguments['--trusted-arn'],
        access_key_id, secret_access_key
        )
    role_adder.add_roles()

if __name__ == '__main__':
    main()
