#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim :set ft=python:

"""
Command line tool to generate afp resources.

Usage:
    afp-resource-maker --config=<file_path> ROLE

Options:
  -h --help               Show this
  --config=<path>         Path to configuation files
                          [default: /etc/afp-resource-maker]
"""

import sys

from docopt import docopt
from yamlreader import yaml_load

from afp_resource_maker import RoleMaker, CanNotContinueException


def main():
    """Main function for script execution"""
    arguments = docopt(__doc__)
    config = yaml_load(arguments['--config'])
    try:
        rolemaker = RoleMaker(config)
        rolemaker.make_role(arguments['ROLE'])
    except CanNotContinueException as error:
        print >> sys.stderr, error
        sys.exit(1)


if __name__ == '__main__':
    main()
